### ISSUE TITLE
Add API tests

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/metacpan-monitoring#2]
Even a few basics... maybe one against each end point...

https://github.com/CPAN-API/cpan-api/blob/master/docs/API-docs.md#search-without-constraints

@oalders anything specific that would be good here?

**Comment by melezhik** [comment]
@oalders , @ranguard  as these new tests are against new host - http://api.metacpan.org , not http://metacpan.org this will require a dedicated test suite and would be better being  kept under distinct repository. I would suggest such a division:

* https://github.com/CPAN-API/metacpan-monitoring - for monitoring, smoke tests - very simple test suite ( we already have it )

* https://github.com/CPAN-API/metacpan-api-test - functional tests for metacpan API ( rest/json API )

What do you think?

PS other than that swat normally assume one host - one test suite schema .

**Comment by ranguard** [comment]
@melezhik good idea - https://github.com/CPAN-API/metacpan-api-test created and how have access
