### ISSUE TITLE
update cron.sh

### ISSUE THREAD

**Issue by melezhik** [CPAN-API/metacpan-monitoring#3]
HI @ranguard  at b78dde6 I have updated cron.sh to clean swat cache file after swat is done.
Could you please pick up a new version (started with this commit ) and ensure that cache files are cleaned.

# How to check this?

## delete old cache files

`rm -f ~/.swat/.cache/` 

## check swat cache directory

 `~/.swat/.cache/` dierctory should be empty

**Comment by melezhik** [comment]
adding @oalders as watcher just in case ...

**Comment by oalders** [comment]
@melezhik thanks for this!

**Comment by ranguard** [comment]
Done, deployed and confirmed
